---

nginx_site_server_address: "{{ vault_nginx_site_server_address }}"
nginx_site_facility_name: "Iltilal Health Center"
nginx_site_facility_mfl_code: 14569
nginx_site_kenyaemr_port: 7070
nginx_site_webadt_port: 6060
