---

nginx_site_server_address: "{{ vault_nginx_site_server_address }}"
nginx_site_facility_name: "Mile 46 Health Centre"
nginx_site_facility_mfl_code: 15185
nginx_site_kenyaemr_port: 7070
nginx_site_webadt_port: 6060
