---

nginx_site_server_address: "{{ vault_nginx_site_server_address }}"
nginx_site_facility_name: "Ruaraka Dispensary"
nginx_site_facility_mfl_code: 13172
nginx_site_kenyaemr_port: 7070
nginx_site_webadt_port: 6060
