---

# app user details
db_backup_user: "{{ vault_db_backup_user }}"
db_backup_user_group: "{{ vault_db_backup_user_group }}"

# host mysql_db credentials. 
db_backup_mysql_host: "{{ vault_db_backup_mysql_host }}"
db_backup_mysql_port: "{{ vault_db_backup_mysql_port }}"
db_backup_mysql_user_password: "{{ vault_db_backup_mysql_user_password }}"

# gcp vars
db_backup_gcp_bucket_location: "{{ vault_db_backup_gcp_bucket_location }}"
db_backup_gcp_bucket_storage_class: "{{ db_backup_gcp_bucket_storage_class }}"
db_backup_gcp_bucket_name: "{{ vault_db_backup_gcp_bucket_name }}"
db_backup_gcp_app_credentials: "{{ vault_db_backup_gcp_app_credentials }}"
