---
# FOR TELEPORT ADMINS:
#
# run sudo tctl tokens add --type=node before running this playbook.
# Also ensure you've placed Teleport vars in a <new_server>.yml file under
# inventories/infrastructure/host_vars
#
# Use the token value and CA pin for this playbook's input prompts.
# ansible-playbook -i inventories/infrastructure -l <new_server> -vvv teleport_node.yml

- name: Setup a Teleport node and app service on an FyJ Facility
  hosts: localhost
  strategy: free
  roles:
      - common
      - teleport

  vars_prompt:

      - name: teleport_node_auth_token
        prompt: Enter Teleport Auth token for the new node
        private: yes

      - name: teleport_master_ca_pin
        prompt: Enter Teleport Master CA Pin
        private: yes

  tasks:

      - name: "Check if required variables have been defined"
        ansible.builtin.fail:
            msg: "{{ item.name }} is not defined"
        when: not item.value
        loop:
            - { name: "teleport_master_ca_pin", value: "{{ teleport_master_ca_pin }}" }
            - { name: "teleport_node_auth_token", value: "{{ teleport_node_auth_token }}" }
            - { name: "teleport_node_env", value: "{{ teleport_node_env }}" }
            - { name: "teleport_node_site_type", value: "{{ teleport_node_site_type }}" }
            - { name: "teleport_node_location", value: "{{ teleport_node_location }}" }
            - { name: "teleport_node_region", value: "{{ teleport_node_region }}" }
        tags: ["teleport_node"]

      - name: "Setup Teleport config file"
        template:
            src: "../../roles/teleport/templates/teleport_node.yaml"
            dest: "/etc/teleport.yaml"
            owner: "root"
            group: "root"
            mode: "u=rw,g=rw,o=r"
        become: true
        tags: ["teleport_node"]

      - name: "Enable Teleport service"
        systemd:
            name: teleport
            enabled: yes
        become: true
        tags: ["teleport_node"]

      # If you're redeploying new Teleport settings to a server with
      # Teleport running, this task will execute but show as failed
      # due to connection problems since the Teleport connection will
      # break on service restart
      - name: "Start Teleport service"
        systemd:
            name: teleport
            state: restarted
        become: true
        tags: ["teleport_node"]
