---

- hosts: sil_pipeline
  tasks:
      - name: "Generate new Teleport certificates for Airflow"
        ansible.builtin.shell: "tctl auth sign --user=airflow --format=openssh --out=/tmp/airflow-teleport --ttl=480h --overwrite"
        delegate_to: 127.0.0.1

      - name: "Push the created certificates to Airflow server"
        copy:
            src: "{{ item }}"
            dest: /home/airflow/.ssh/
            owner: airflow
            group: airflow
            mode: '0600'
        loop:
            - /tmp/airflow-teleport
            - /tmp/airflow-teleport-cert.pub
        become: true
