---

- name: Install and set up IDR client application
  hosts: idr_client_hosts
  roles:
    - common
    - idr_client
  strategy: free
  vars:
    # Location details
    idr_client_location_code: "{{ nginx_site_facility_mfl_code }}"
    idr_client_location_name: "{{ nginx_site_facility_name }}"
