---

- name: Install and set up CHAI WebADT on an Ubuntu 20.04 LTS server
  hosts: web_adt_servers
  pre_tasks:
    - name: Create deploy user
      ansible.builtin.user: name={{ deploy_user }} groups=www-data,sudo state=present system=yes
      become: yes
    - name: Add application user group
      ansible.builtin.group: name={{ web_adt_application_user_group }} state=present system=yes
      become: yes
    - name: Add application user
      ansible.builtin.user: create_home=yes group={{ web_adt_application_user_group }} home=/home/{{ web_adt_application_user }} name={{ web_adt_application_user }} shell=/bin/bash state=present system=yes
      become: yes
  roles:
    - common
    - role: apache_httpd
      vars:
        apache_httpd_instance_name: "{{ web_adt_application_name }}"
        apache_httpd_listen_address: "{{ web_adt_application_server_listening_address }}"
        apache_httpd_server_user: "{{ web_adt_application_user }}"
        apache_httpd_server_user_group: "{{ web_adt_application_user_group }}"
  strategy: free
  vars:
    deploy_user: deploy
  
  tasks:
    - name: Install and set up WebADT
      import_role:
        name: web_adt
      vars:
        web_adt_apache_httpd_config_extras_dir: "{{ apache_httpd_config_extras }}"
        web_adt_apache_httpd_document_root: "{{ apache_httpd_document_root }}"
        web_adt_apache_httpd_listen_address: "{{ apache_httpd_listen_address }}"
        web_adt_apache_httpd_logs_root: "{{ apache_httpd_logs_root }}"
        web_adt_apache_httpd_server_user: "{{ web_adt_application_user }}"
        web_adt_apache_httpd_server_user_group: "{{ web_adt_application_user_group }}"
        web_adt_db_name: "{{ web_adt_application_database_name }}"
        web_adt_db_user: "{{ web_adt_application_database_user }}"
        web_adt_db_user_password: "{{ web_adt_application_database_user_password }}"
      tags: ["web_adt_application"]

    - name: Enable and restart WebADT application service
      ansible.builtin.systemd_service:
        daemon_reload: yes
        enabled: yes
        force: yes
        name: "{{ web_adt_application_name }}.service"
        scope: system
        state: restarted
      become: yes
      tags: ["web_adt_application"]
