---
#--------------------------------------------------------------------
#    - install nginx.
#    - install certbot.
#    - obtaining ssl certificate for *.app_name.cloud.fahariyajamii.org domain.
#    - change letsencrypt_cert_domain_suffix value to generate cert for other domains.
#    - remember to first create the required recordset for which you're obtaining the cert.
#--------------------------------------------------------------------

- hosts: central_server1
  name: Configure nginx reverse proxy
  roles:
      - role: nginx
        nginx_sites_enabled: /etc/nginx/sites-enabled/*/*.conf
      - role: certbot
        certbot_email: "{{ certbot_email }}"
      - role: letsencrypt_cert
        certificate_domain: "{{ letsencrypt_cert_domain_suffix }}"
